[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "numpy>=2.3.1",
    "plotly>=6.2.0",
    "prophet>=1.1.7",
    "requests>=2.32.4",
    "streamlit-autorefresh>=1.0.1",
    "streamlit>=1.46.1",
    "trafilatura>=2.0.0",
    "pandas>=2.3.0",
    "openai>=1.93.0",
    "selenium>=4.34.0",
    "webdriver-manager>=4.0.2",
    "holidays>=0.75",
    "yfinance>=0.2.64",
    "newspaper3k>=0.2.8",
    "pytz>=2025.2",
    "chardet>=5.2.0",
    "pillow>=11.2.1",
]
